server:
  port: 7003


spring:
  application:
    name: hui-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.157.129:8848
    gateway:
      discovery:
        locator:
          # 开启gateway从nacos上获取服务列表
          enabled: true
      routes:
      - id: my-security
        uri: lb://hui-security #权限
        # ① 以http://localhost:8090/security/** 的访问路径会转发到hui-security微服务的/**
        predicates:
          - Path=/security/**

#开启acutor端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      #打开端点详情
      show-details: always
